// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmngKl1V4YBNht9V8dsPU6674jm2CLA0',
    appId: '1:175099287010:web:5978d8167981f28d5d15bb',
    messagingSenderId: '175099287010',
    projectId: 'prakflutterfirebase-2324',
    authDomain: 'prakflutterfirebase-2324.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-2324.appspot.com',
    measurementId: 'G-3H0D06RFN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9OwLr8qyty4QV6ZuG4HgH7y_upFwBJ4M',
    appId: '1:175099287010:android:6f248dd462cf36f45d15bb',
    messagingSenderId: '175099287010',
    projectId: 'prakflutterfirebase-2324',
    storageBucket: 'prakflutterfirebase-2324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJsCcRss-HlAYhyhoW8xRiatGcq_x1_k',
    appId: '1:175099287010:ios:770cdafc3b15836f5d15bb',
    messagingSenderId: '175099287010',
    projectId: 'prakflutterfirebase-2324',
    storageBucket: 'prakflutterfirebase-2324.appspot.com',
    iosClientId: '175099287010-89bfupb4gihh1okffpklgktsclbs6k6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJsCcRss-HlAYhyhoW8xRiatGcq_x1_k',
    appId: '1:175099287010:ios:770cdafc3b15836f5d15bb',
    messagingSenderId: '175099287010',
    projectId: 'prakflutterfirebase-2324',
    storageBucket: 'prakflutterfirebase-2324.appspot.com',
    iosClientId: '175099287010-89bfupb4gihh1okffpklgktsclbs6k6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjmngKl1V4YBNht9V8dsPU6674jm2CLA0',
    appId: '1:175099287010:web:6c61dc5eb0011aeb5d15bb',
    messagingSenderId: '175099287010',
    projectId: 'prakflutterfirebase-2324',
    authDomain: 'prakflutterfirebase-2324.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-2324.appspot.com',
    measurementId: 'G-136CNSDXB2',
  );
}
